export const ALL_NOTES_REQUEST = "ALL_NOTES_REQUEST"
export const ALL_NOTES_SUCCESS = "ALL_NOTES_SUCCESS"
export const ALL_NOTES_FAIL = "ALL_NOTES_FAIL"

export const SINGLE_NOTE_REQUEST = "SINGLE_NOTE_REQUEST"
export const SINGLE_NOTE_SUCCESS = "SINGLE_NOTE_SUCCESS"
export const SINGLE_NOTE_FAIL = "SINGLE_NOTE_FAIL"


export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST"
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS"
export const CREATE_NOTE_FAIL = "CREATE_NOTE_FAIL"


export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST"
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS"
export const UPDATE_NOTE_RESET = "UPDATE_NOTE_RESET"
export const UPDATE_NOTE_FAIL = "UPDATE_NOTE_FAIL"


export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST"
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"
export const DELETE_NOTE_RESET = "DELETE_NOTE_RESET"
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL"



export const CLEAR_ERRORS = "CLEAR_ERRORS";